default: &default
  adapter: postgresql
  template: template0
  encoding: UTF8
  username: postgres
  password:
  pool: 5
  # TODO: https://devcenter.heroku.com/articles/concurrency-and-database-connections
  timeout: 5000

development:
  <<: *default
  database: pstage_development

test:
  <<: *default
  database: pstage_test

production:
  <<: *default
  database: pstage_production
  username: pstage
  password: <%= ENV['DB_PASS'] %>
